### ISSUE TITLE
Error: reading PAT token from keyring failed: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)

### ISSUE THREAD

**Issue by sylvaindethier** [anchordotdev/cli#14]
**Are there any additional details you would like to share?**

---

**Command:** `config`
**Version:** `0.0.30 (linux/amd64) Commit: bce01483e83d79153b9a4a0040f1142a85e1758f BuildDate: 2024-05-02T20:51:28Z`
**Arguments:** `[]`
**Flags:** `[]`
**Stdout:**
```
    * Checking authentication: probing credentials locally…[38;5;61m⠋[0m
```

**Comment by geemus** [comment]
Thanks for the details and for giving it another try. I think we made some progress, but looks like we have a little more work to do still. I'll take another look presently.

**Comment by geemus** [comment]
I believe that in part the issue is that we try to use gnome-keyring if it's available, but it's harder to deal with it when it's present but not working. So if you now uninstall gnome-keyring I think things will work, though it will ask you to signin with each command (since it won't be able to store the credentials). I'll try to work on a better fix for your particular case as well, but wanted to share this to hopefully unblock you right away.

**Comment by geemus** [comment]
Thanks again for your patience and taking the time to share the errors you are seeing with us so that we can work through them. We've tried again and I think if you bump again to v0.0.31 you should have better luck now. Please reach out again if you have any further issues or feedback, thanks!

**Comment by sylvaindethier** [comment]
You're right ! Having `gnome-keyring` installed on WSL causes the issue.
v0.30.0 works fine without `gnome-keyring`.
I've upgraded to v0.31.0. It worked fine too when `gnome-keyring` is installed.

Thanks !

**Comment by geemus** [comment]
Glad to hear it, thanks for the update and confirming things are now working as we expected.
